theme = "solarized-dark"
icons = "awesome"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1


[[block]]
block = "music"
buttons = ["play", "next"]
marquee_interval = 10
marquee_speed = 0.4

#[[block]]
#block = "net"
#device = "wlp2s0"
##ssid = true
##ip = true
#speed_up = true
##graph_up = true
#interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "07b31b26d5c719f1d52388fdd706ac26", city_id =  "6077243", units = "metric" }

[[block]]
block = "pacman"
interval = 10